<html>
<!--
	INPUT:	i18n_title, i18n_subtitle, header, footer, content
	OUTPUT: 
-->
<head>
	<!--Title structure: CleverFigures | PageName-->
	<title> CleverFigures | <?=$i18n_title?> </title>
	<link rel="stylesheet" type="text/css" href="css/styles.css" media="screen" />
</head>
<body>
	<!--Loads the header-->
	<?=$header?>
	
	<!--Loads title and subtitle-->
	<h1><?=$i18n_title?></h1>
	<h2><?=$i18n_subtitle?></h2>
	
	<!--Loads content. Completely generated by controller-->
	<?=$content?>
	
	<!--Loads footer-->
	<?=$footer?>
</body>
</html>  